[package]
name = "buzz-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buzz-cli"
path = "src/main.rs"

[dependencies]
buzz-core = { path = "../buzz-core" }
qfz3 = { git = "https://github.com/zerocopies/qfz3.git", rev = "4f426e663550cf70663d468c4822a82b5e9df941" }
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
crossterm = "0.27"
reqwest = { version = "0.12", features = ["json", "stream"] }
futures-util = "0.3"
serde_json = "1.0.151"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
